apiVersion: v1
kind: Service
metadata:
  name: test-ssh
  namespace: myvms
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 22
      protocol: TCP
  selector:
    kubevirt.io/domain: testvm
  type: NodePort
